# Profile information
name: LRodrigo - Dicas para o dia a dia
title: LRodrigo:Website
description: > 
  Dicas para o dia a dia
permalink: ':title/'
baseurl: "/blogfresh" 

url: "https://luisrodrigoog.github.io" 

# Social
facebook: luisrodrigoog
twitter: luisrodrigoog
google-plus: luisrodrigoog
github: luisrodrigoog

# Contact form
email: luisrodrigoog@gmail.com

# Comments
discus-identifier: luisrodrigoog

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
